// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrVNOeNv5z386Qu7j8Hykpe0lKfSEh8ss',
    appId: '1:1059231977491:web:faa5d12aa134d738a32fe6',
    messagingSenderId: '1059231977491',
    projectId: 'real-post-app-firebase',
    authDomain: 'real-post-app-firebase.firebaseapp.com',
    databaseURL: 'https://real-post-app-firebase-default-rtdb.firebaseio.com',
    storageBucket: 'real-post-app-firebase.appspot.com',
    measurementId: 'G-ZMBHN06RK3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4N2SBc-LuJsliUMyyi4HQeV6tEbz-NME',
    appId: '1:1059231977491:android:48aafd18c7c53b2fa32fe6',
    messagingSenderId: '1059231977491',
    projectId: 'real-post-app-firebase',
    databaseURL: 'https://real-post-app-firebase-default-rtdb.firebaseio.com',
    storageBucket: 'real-post-app-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl5DuO5phPgVLbDq0FDKfOfTEtGx--zYA',
    appId: '1:1059231977491:ios:016b933b1abe453da32fe6',
    messagingSenderId: '1059231977491',
    projectId: 'real-post-app-firebase',
    databaseURL: 'https://real-post-app-firebase-default-rtdb.firebaseio.com',
    storageBucket: 'real-post-app-firebase.appspot.com',
    iosBundleId: 'com.jurakuziyev.firebaseCrashlytics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAl5DuO5phPgVLbDq0FDKfOfTEtGx--zYA',
    appId: '1:1059231977491:ios:bd8c9905a9984141a32fe6',
    messagingSenderId: '1059231977491',
    projectId: 'real-post-app-firebase',
    databaseURL: 'https://real-post-app-firebase-default-rtdb.firebaseio.com',
    storageBucket: 'real-post-app-firebase.appspot.com',
    iosBundleId: 'com.jurakuziyev.firebaseCrashlytics.RunnerTests',
  );
}
